# Generated by Django 2.2.3 on 2020-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191031_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='TransactionId',
            field=models.CharField(default='', max_length=111),
        ),
    ]
